import type { Car } from '@/types';

export const CARS: Car[] = [
  {
    id: 'c1',
    name: 'Model 3',
    brand: 'Tesla',
    category: 'Electric',
    pricePerDay: 95,
    seats: 5,
    transmission: 'Automatic',
    fuel: 'Electric',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=900&auto=format&fit=crop',
    rating: 4.9,
    available: true,
    description: 'A sleek all-electric sedan with autopilot, premium interior, and 350+ miles of range.',
    features: ['Autopilot', 'Glass Roof', 'Premium Audio', 'Heated Seats', 'Fast Charging'],
  },
  {
    id: 'c2',
    name: 'Civic',
    brand: 'Honda',
    category: 'Economy',
    pricePerDay: 45,
    seats: 5,
    transmission: 'Automatic',
    fuel: 'Petrol',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=900&auto=format&fit=crop',
    rating: 4.6,
    available: true,
    description: 'Reliable and fuel-efficient compact sedan, perfect for city driving and weekend trips.',
    features: ['Apple CarPlay', 'Lane Assist', 'Bluetooth', 'Backup Camera'],
  },
  {
    id: 'c3',
    name: 'X5',
    brand: 'BMW',
    category: 'SUV',
    pricePerDay: 130,
    seats: 7,
    transmission: 'Automatic',
    fuel: 'Diesel',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop',
    rating: 4.8,
    available: true,
    description: 'A luxurious mid-size SUV with three rows of seating and powerful diesel engine.',
    features: ['Leather Seats', 'Panoramic Roof', 'Adaptive Cruise', '4x4'],
  },
  {
    id: 'c4',
    name: '911 Carrera',
    brand: 'Porsche',
    category: 'Sports',
    pricePerDay: 320,
    seats: 2,
    transmission: 'Automatic',
    fuel: 'Petrol',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&auto=format&fit=crop',
    rating: 5.0,
    available: true,
    description: 'Iconic sports car delivering thrilling performance and timeless design.',
    features: ['Sport Chrono', 'Bose Audio', 'Launch Control', 'Carbon Trim'],
  },
  {
    id: 'c5',
    name: 'S-Class',
    brand: 'Mercedes-Benz',
    category: 'Luxury',
    pricePerDay: 220,
    seats: 5,
    transmission: 'Automatic',
    fuel: 'Hybrid',
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=900&auto=format&fit=crop',
    rating: 4.9,
    available: true,
    description: 'The benchmark in luxury sedans with massage seats, ambient lighting, and whisper-quiet cabin.',
    features: ['Massage Seats', 'Ambient Lighting', 'Burmester Audio', 'Night Vision'],
  },
  {
    id: 'c6',
    name: 'Sprinter',
    brand: 'Mercedes-Benz',
    category: 'Van',
    pricePerDay: 110,
    seats: 9,
    transmission: 'Manual',
    fuel: 'Diesel',
    image: 'https://images.unsplash.com/photo-1609520778763-fae9bd0bb1e3?w=900&auto=format&fit=crop',
    rating: 4.5,
    available: true,
    description: 'Spacious 9-seater van ideal for group trips, family vacations, and airport transfers.',
    features: ['9 Seats', 'AC', 'USB Ports', 'Large Cargo'],
  },
  {
    id: 'c7',
    name: 'Mustang GT',
    brand: 'Ford',
    category: 'Sports',
    pricePerDay: 150,
    seats: 4,
    transmission: 'Manual',
    fuel: 'Petrol',
    image: 'https://images.unsplash.com/photo-1547245324-d777c6f05e80?w=900&auto=format&fit=crop',
    rating: 4.7,
    available: true,
    description: 'American muscle with a roaring V8 and unmistakable style.',
    features: ['V8 Engine', 'Sport Mode', 'Launch Control', 'Premium Audio'],
  },
  {
    id: 'c8',
    name: 'Corolla',
    brand: 'Toyota',
    category: 'Economy',
    pricePerDay: 38,
    seats: 5,
    transmission: 'Automatic',
    fuel: 'Hybrid',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=900&auto=format&fit=crop',
    rating: 4.5,
    available: false,
    description: 'Hybrid economy car with outstanding fuel economy and modern safety features.',
    features: ['Hybrid', 'Toyota Safety Sense', 'Apple CarPlay', 'Backup Camera'],
  },
];
